# Generated by Django 2.2.4 on 2020-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ')),
                ('image', models.FileField(upload_to='', verbose_name='画像')),
                ('price', models.PositiveIntegerField(verbose_name='画像')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('review', models.TextField(blank=True, null=True, verbose_name='口コミ')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
            ],
        ),
    ]
