# Generated by Django 2.2.4 on 2020-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(1, '飲料'), (2, '生花')], verbose_name='カテゴリ'),
        ),
    ]
