# Generated by Django 2.2.4 on 2020-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200510_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='like',
        ),
        migrations.RemoveField(
            model_name='item',
            name='review',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(verbose_name='値段'),
        ),
    ]
